### ISSUE TITLE
Thanks for your nice project <3

### ISSUE THREAD

**Issue by pi0** [charlieduong94/radix-router#35]
Hi @charlieduong94! Just created this issue to thank you for your nice project that helped me to create [radix3](https://github.com/unjs/radix3) 💚 We plan to use it for [h3](https://github.com/unjs/h3) that is finally used in [Nuxt 3](https://v3.nuxtjs.org/). The fork is basically a rewrite with typescript with ESM support and also simplified lookup format (only returning data) to help little bit more optimizations and avoid object creation on lookups.

**Comment by ctdio** [comment]
Hey @pi0! Thanks for reaching out to let me know! I'm happy you were able to get some value out of this project! ❤️
